services:
  - type: web
    name: fatuma-whatsapp-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.mjs
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
